openapi: 3.0.3
info:
  title: Core E-commerce API
  version: 1.0.0
  description: API for core e-commerce functionality
servers:
  - url: https://api.ogni.com/v1
paths:
  /products:
    get:
      summary: Get products
      parameters:
        - name: category
          in: query
          schema:
            type: string
        - name: search
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  total:
                    type: integer
    post:
      summary: Create product (admin)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Product created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /products/{id}:
    get:
      summary: Get product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    put:
      summary: Update product (admin)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '200':
          description: Product updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /categories:
    get:
      summary: Get categories
      responses:
        '200':
          description: List of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
  /cart:
    get:
      summary: Get user cart
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Cart contents
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
    post:
      summary: Add item to cart
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                quantity:
                  type: integer
                  minimum: 1
      responses:
        '201':
          description: Review added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
  /notifications:
    post:
      summary: Subscribe to push notifications
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: FCM token for push notifications
      responses:
        '200':
          description: Subscription successful
    delete:
      summary: Unsubscribe from push notifications
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Unsubscription successful
  /analytics/events:
    post:
      summary: Track user interaction events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eventType:
                  type: string
                  enum: [page_view, click, scroll, form_submit, search, add_to_cart, purchase]
                page:
                  type: string
                element:
                  type: string
                metadata:
                  type: object
                sessionId:
                  type: string
                timestamp:
                  type: string
                  format: date-time
      responses:
        '200':
          description: Event tracked successfully
  /analytics/session:
    post:
      summary: Start user session tracking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sessionId:
                  type: string
                userId:
                  type: string
                deviceInfo:
                  type: object
                referrer:
                  type: string
      responses:
        '200':
          description: Session started
    put:
      summary: Update session data
      parameters:
        - name: sessionId
          in: query
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                duration:
                  type: integer
                pageViews:
                  type: integer
                endTime:
                  type: string
                  format: date-time
      responses:
        '200':
          description: Session updated
  /feed:
    get:
      summary: Get personalized product feed
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Personalized feed of products
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  nextOffset:
                    type: integer
  /products/{id}/like:
    post:
      summary: Like a product
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                context:
                  type: string
                  enum: [feed, product_page, search]
      responses:
        '201':
          description: Product liked
    delete:
      summary: Unlike a product
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product unliked
  /feed/interactions:
    post:
      summary: Track feed interaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                interactionType:
                  type: string
                  enum: [view, like, skip, click, add_to_cart, purchase]
                feedPosition:
                  type: integer
                sessionId:
                  type: string
      responses:
        '200':
          description: Interaction tracked
  /products/{id}/comments:
    get:
      summary: Get product comments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: List of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductComment'
    post:
      summary: Add comment to product
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  maxLength: 500
                parentId:
                  type: string
      responses:
        '201':
          description: Comment added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductComment'
  /products/{id}/share:
    post:
      summary: Share product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                platform:
                  type: string
                  enum: [whatsapp, telegram, email, copy_link, native_share]
      responses:
        '200':
          description: Share tracked
  /wishlist:
    get:
      summary: Get user wishlist
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User wishlist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wishlist'
    post:
      summary: Add product to wishlist
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
      responses:
        '200':
          description: Product added to wishlist
    delete:
      summary: Remove product from wishlist
      security:
        - bearerAuth: []
      parameters:
        - name: productId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product removed from wishlist
  /cart/items/{productId}:
    delete:
      summary: Remove item from cart
      security:
        - bearerAuth: []
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Item removed
  /checkout:
    post:
      summary: Create order from cart
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                shippingAddress:
                  type: object
                  properties:
                    street: {type: string}
                    city: {type: string}
                    zip: {type: string}
                paymentMethod:
                  type: string
                  enum: [pix, card]
      responses:
        '201':
          description: Order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
  /orders:
    get:
      summary: Get user orders
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
  /orders/{id}:
    get:
      summary: Get order details
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
components:
  schemas:
    Product:
      type: object
      properties:
        id: {type: string}
        name: {type: string}
        description: {type: string}
        price: {type: number}
        images: {type: array, items: {type: string}}
        stock: {type: integer}
        categoryId: {type: string}
    ProductInput:
      type: object
      properties:
        name: {type: string}
        description: {type: string}
        price: {type: number}
        images: {type: array, items: {type: string}}
        stock: {type: integer}
        categoryId: {type: string}
    Category:
      type: object
      properties:
        id: {type: string}
        name: {type: string}
        description: {type: string}
        image: {type: string}
    Cart:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              productId: {type: string}
              quantity: {type: integer}
    Order:
      type: object
      properties:
        id: {type: string}
        items: {type: array, items: {$ref: '#/components/schemas/OrderItem'}}
        total: {type: number}
        status: {type: string, enum: [pending, paid, shipped, delivered, cancelled]}
        shipping: {type: object}
        payment: {type: object}
    OrderItem:
      type: object
      properties:
        productId: {type: string}
        quantity: {type: integer}
        price: {type: number}
    Review:
      type: object
      properties:
        id: {type: string}
        userId: {type: string}
        rating: {type: integer}
        comment: {type: string}
        createdAt: {type: string, format: date-time}
    ProductComment:
      type: object
      properties:
        id: {type: string}
        userId: {type: string}
        productId: {type: string}
        content: {type: string}
        createdAt: {type: string, format: date-time}
        updatedAt: {type: string, format: date-time}
    ProductShare:
      type: object
      properties:
        id: {type: string}
        userId: {type: string}
        productId: {type: string}
        platform: {type: string, enum: [whatsapp, telegram, email, copy_link, native_share]}
        createdAt: {type: string, format: date-time}
    Wishlist:
      type: object
      properties:
        id: {type: string}
        userId: {type: string}
        products: {type: array, items: {type: string}}
        createdAt: {type: string, format: date-time}
        updatedAt: {type: string, format: date-time}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT